<footer>
  <div>
    <div>
      <div>
        <div>
          <h6>History</h6>
          <button type="button" data-bs-toggle="tooltip" data-bs-placement="bottom">
            <i>history</i>
          </button>
        </div>
      </div>
      <div>
        <div>
          <table>
            <thead>
              <tr>
                <th>Event</th>
                <th>User</th>
                <th>Time</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <p>1. User "Abc" added</p>
                </td>
                <td>
                  <p>345</p>
                </td>
                <td>
                  <p>00:17:07</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p>2. User "Abc" changed</p>
                </td>
                <td>
                  <p>520</p>
                </td>
                <td>
                  <p>00:23:13</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p>3. User "Abc" removed by 123</p>
                </td>
                <td>
                  <p>122</p>
                </td>
                <td>
                  <p>00:3:10</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p>4. User "Abc" added</p>
                </td>
                <td>
                  <p>1,900</p>
                </td>
                <td>
                  <p>00:30:42</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p>5.User "Abc" added</p>
                </td>
                <td>
                  <p>1,442</p>
                </td>
                <td>
                  <p>00:31:50</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p>6. User "Abc" added</p>
                </td>
                <td>
                  <p>201</p>
                </td>
                <td>
                  <p>00:12:42</p>
                </td>
              </tr>
              <tr>
                <td>
                  <p>7. User "Abc" added</p>
                </td>
                <td>
                  <p>2,115</p>
                </td>
                <td>
                  <p>00:50:11</p>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</footer>